/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;

import com.sun.glass.events.KeyEvent;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author falco
 */
public class Cliente extends javax.swing.JFrame {

    String nombre;
    public static Socket socket;
    DataOutputStream salida;
    /**
     * Creates new form Cliente
     */
    public Cliente(String nombre, int puerto,String direccion) {
        try {
            socket = new Socket(direccion,puerto);
            this.salida = new DataOutputStream(socket.getOutputStream());
            this.nombre = nombre;
            hiloChats hc = new hiloChats(this, socket);
            Thread t = new Thread(hc);
            t.start();
        } catch (IOException ex) {
            System.out.println("No se pudo prro: "+ex.getMessage());
        }
        initComponents();
    }
    
    public void agregarMSN(String cad){
        tMensajes.setText(tMensajes.getText()+cad);
    }

    private Cliente(Socket socket) {
        
        
        try {
            this.socket = socket;
            this.salida = new DataOutputStream(socket.getOutputStream());
        } catch (IOException ex) {
            System.out.println("No se pudo we: "+ex.getMessage());
        }
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tMensajes = new javax.swing.JTextArea();
        tEnvio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jScrollPane1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        tMensajes.setColumns(20);
        tMensajes.setRows(5);
        tMensajes.setEnabled(false);
        jScrollPane1.setViewportView(tMensajes);

        tEnvio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tEnvioKeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tEnvio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            salida.writeUTF(nombre+" dice:"+tEnvio.getText());
            //agregarMSN(nombre+" dice:"+tEnvio.getText()+"\n");
            tEnvio.setText("");
        } catch (IOException ex) {
            System.out.println("Hubo un error alv: "+ ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tEnvioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tEnvioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                salida.writeUTF(nombre + " dice:" + tEnvio.getText());
                //agregarMSN(nombre + " dice:" + tEnvio.getText() + "\n");
                tEnvio.setText("");
            } catch (IOException ex) {
                System.out.println("Hubo un error alv: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_tEnvioKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente(socket).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tEnvio;
    private javax.swing.JTextArea tMensajes;
    // End of variables declaration//GEN-END:variables
}
